on:
  workflow_dispatch:
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'gluonhq/gluon-samples'
          ref: '728b1b9687c6cc26019aac240aa37fb5c7ce4b0c'
      - uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          graalvm: '22.1.0.1-Final'
          jdk: 'java17'
          arch: aarch64
      - working-directory: ./HelloGluon
        run: mvn -Pios gluonfx:build
